language: java

# Trying to get a newer Java 8 version than u31...
addons:
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java9-installer

before_install:
  - export JAVA9_HOME=/usr/lib/jvm/java-9-oracle


jdk: oraclejdk8


